[supabase]
url = "https://hnsocqcrrabppwcaalau.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhuc29jcWNycmFicHB3Y2FhbGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODc2NTMsImV4cCI6MjA2NTY2MzY1M30.06lj57uGREW5CbQAU21GnBYY6FcAPhsHhQXfRnAT_js"
